### ISSUE TITLE
[Feature Request] To be able to specify `--category` for scanning code violations in Extension Settings

### ISSUE THREAD

**Issue by vc4u** [forcedotcom/sfdx-code-analyzer-vscode#10]
**Is your feature request related to a problem? Please describe.**
By default the scan finds and flags almost every violations and warning which could be overwhelming for a large class.

**Describe the solution you'd like**
It would help ISVs, to be able to scan for just "Security" category so as to be ready to generate report for Security Review submission.

"Workaround": 
Executing via CLI allows category argument to scan only for Security concerns. 

"Urgency": 
Nice to have

**Comment by jfeingold35** [comment]
@vc4u , in the long-term, we may add some mechanism to more finely control which rules run in the extension. But for now, per the documentation, you could create a custom PMD config file that includes only the Security rules, and reference that in the extension's settings. Then only those rules will run.

**Comment by johnbelosf** [comment]
This is now available in the latest version
