### ISSUE TITLE
[BUG] Option to scan via DFA is not visible on Visual Studio Code

### ISSUE THREAD

**Issue by victorng8** [forcedotcom/sfdx-code-analyzer-vscode#127]
### Have you verified this is Salesforce Code Analyzer Extension specific?

Yes

### Bug Description

`SFDX: Scan selected method with Graph Engine path-based analysis.` not visible

### Steps To Reproduce

I was following this [guide](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/code-analyzer-vs-code-extension.html#scan-your-code-using-salesforce-graph-engine) 

1. Open a file in the VS Code Editor.
2. Right-click on the method that you want to scan.
3. Select `SFDX: Scan selected method with Graph Engine path-based analysis.`

However on Step 3 I do not see this option at all

### Expected Behavior

I expect that on Step 3 that I can view that option and use that option on the file/folder

### Operating System

MacOS Sonoma 14.6.1

### Visual Studio Code Version

Version: 1.92.2 (Universal)

### Salesforce Code Analyzer Extension Version

v1.1.0

### Salesforce CLI Version

@salesforce/cli/2.56.7 darwin-arm64 node-v20.16.0

### Code Analyzer CLI Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.5.0

### Additional Context (Screenshots, Files, etc)

![Screenshot 2024-09-02 at 10 34 51 PM](https://github.com/user-attachments/assets/0bb0ccd3-ac2d-4046-8f22-a73e57e9a492)

### Workaround

The command line version of dfa

### Urgency

High

**Comment by jag-j** [comment]
@victorng8 : Are you right clicking on the method while you are in the editor? From the attached screenshot, it looks like you are right-clicking on the side panel. We do not provide this command there.

**Comment by jag-j** [comment]
@victorng8 Closing this for now. Please feel free to reopen this if you still see this issue.
