### ISSUE TITLE
[BUG] Extension doesn't find issue.

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-code-analyzer-vscode#131]
I am running the extension on this repo and expect the pmd-appexchange engine to report this line https://github.com/rsoesemann/unhappy-soup/blob/master/force-app/main/default/classes/Voldemort.cls#L41

![Screenshot 2024-09-17 at 16 52 40](https://github.com/user-attachments/assets/6a2dd9d0-4334-45a0-a7f7-e2f4897f6491)
![Screenshot 2024-09-17 at 16 47 36](https://github.com/user-attachments/assets/f5688a7e-42eb-4545-80bc-164214869f8f)
![Screenshot 2024-09-17 at 16 41 34](https://github.com/user-attachments/assets/29f735f8-51c7-4979-835c-19398fa16857)
![Screenshot 2024-09-17 at 16 41 07](https://github.com/user-attachments/assets/5d685bcf-19b8-45ef-97a6-be2cb2702ffe)

**Comment by jag-j** [comment]
@rsoesemann - We notice that when 'pmd-appexchange' is the only engine specified, it works as expected. It doesn't work when combined with other engines as you have here.

**Comment by rsoesemann** [comment]
@jag-j thank for confirming. Can you say when this will be fixed approximately?

**Comment by jag-j** [comment]
@rsoesemann: Apologies for the delay. Do you still see this issue? I cannot repro this with the latest version of the extension. 
<img width="849" alt="Screenshot 2024-10-03 at 7 14 43 AM" src="https://github.com/user-attachments/assets/74c98684-2157-47d2-9e97-f4657dc42c0f">

**Comment by tehnrd** [comment]
I thought this wasn't working for me but I needed to clear Categories. This may sync across VSCode projects if you've enabled setting sync.

<img width="812" alt="Screenshot 2024-10-14 at 10 37 19 PM" src="https://github.com/user-attachments/assets/dabbd1e9-6908-4346-a01f-bb47b3dbf752">

I had Security and expected some issues to show like not using `UserInfo.getSessionId();` but that is Best Practice category, not Security.
