### ISSUE TITLE
[Feature Request] Run static analysis of file open / save

### ISSUE THREAD

**Issue by ggiralsfdc** [forcedotcom/sfdx-code-analyzer-vscode#16]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like code analyzer to run when I either open / save a file, to avoid having to manually run the analysis.

**Describe alternatives you've considered**
In the case of Apex PMD, this is something that is already implemented in another extensions.

"Workaround": Running the static analysis manually.

"Urgency": Highly beneficial.

**Comment by jfeingold35** [comment]
@ggiralsfdc , this is already an item on our backlog. I'll tie this to that item, and we'll make sure to let you know as soon as it's implemented.

**Comment by jag-j** [comment]
@ggiralsfdc - this feature is now available. Please refer to https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/code-analyzer-vs-code-extension.html#activate-scans-on-save-or-on-open on how to turn this feature on. Thank you!

**Comment by ggiralsfdc** [comment]
Works great, thank you :)
