### ISSUE TITLE
Unable to install salesforce code Analyzer

### ISSUE THREAD

**Issue by nikhil-capita** [forcedotcom/sfdx-code-analyzer-vscode#47]
Type: <b>Bug</b>

Hi Team,

I am trying to install salesforce code scanner using below command
sfdx plugins:install @salesforce/sfdx-scanner

But I am getting below error -
Polling for new version(s) to become available on npm... done
RequestError: unable to get local issuer certificate
Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

Could you please help me to fix this.

Thanks,
Nikhil

Extension version: 0.4.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (21.59GB free)|
|Process Argv|--crash-reporter-id 5fd7c251-4c7c-495a-a27a-465804a18f63|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
dsvsc020:30973508

```

</details>

**Comment by stephen-carter-at-sf** [comment]
This issue is not specific to Salesforce Code Analyzer but instead is an issue with your machine not being able to communicate correctly with npm or an issue with the sf plugins install command. Please reroute your issue to the correct github repo (possibly https://github.com/forcedotcom/cli) if you are still having issues.
