### ISSUE TITLE
Code Analyzer not working

### ISSUE THREAD

**Issue by debprotim** [forcedotcom/sfdx-code-analyzer-vscode#57]
**Describe the bug**
2024-03-26 17:12:46.512 [info] Registered command as part of sfdx-code-analyzer-vscode activation.
2024-03-26 17:12:46.520 [info] Registered scanOnSave as part of sfdx-code-analyzer-vscode activation.
2024-03-26 17:12:46.523 [info] Extension sfdx-code-analyzer-vscode activated.
2024-03-26 17:27:43.388 [info] Registered command as part of sfdx-code-analyzer-vscode activation.
2024-03-26 17:27:43.391 [info] Registered scanOnSave as part of sfdx-code-analyzer-vscode activation.
2024-03-26 17:27:43.393 [info] Extension sfdx-code-analyzer-vscode activated.
2024-03-27 16:23:19.245 [error] 
2024-03-27 16:24:29.759 [error] 

**To Reproduce**
Click on a file and select SF: Scan current file Code Analyzer

**Expected behavior**
Code analyzer to show report on any error or issues.

**Screenshots**
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/9b0c6106-7a25-45ef-bcd2-79381871337c)

**Desktop (please complete the following information):**
VSCode
Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

"Urgency": "Not business-stopping".

**Comment by jfeingold35** [comment]
@debprotim , question: Do you have the [Salesforce Extension Pack](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) installed?

**Comment by debprotim** [comment]
@jfeingold35 yes, I do have it installed.

![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/848a556f-2a6d-417d-932b-d3c1682008d7)

**Comment by jfeingold35** [comment]
@debprotim , when you use the "scan the current file" command, a popup should appear in the corner that says something like "running code analyzer", and if there's an error then it should be replaced with an error message. Do you see either of those boxes?

**Comment by debprotim** [comment]
Is this what you are mentioning?
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/38721b0e-61cb-47e8-b636-cd661da2d714)
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/8b89bf8b-029b-46f1-9735-8da0c5ad6bd5)

**Comment by jfeingold35** [comment]
@debprotim , yes. If you expand the error box, is there a more detailed message?

**Comment by debprotim** [comment]
The screenshot I have attached is in expanded form itself. And it shows nothing other than "Analysis Failed:"

**Comment by debprotim** [comment]
on running the command, it started installing the plugin, but plugin installation is failing with following error:

![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/825af151-a7fb-4be0-8d14-7b2e1f6c9ff8)

**Comment by debprotim** [comment]
somehow any other version for me is running into following loop:
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8632083/0a2f9e34-f0b7-46c7-ad0d-28708f07c8ae)

**Comment by jfeingold35** [comment]
@debprotim , are you on the latest version of `sf`? I can't really think of any other thing that might be causing that.

**Comment by debprotim** [comment]
I am at @salesforce/cli/2.32.8 win32-x64 node-v18.18.0

**Comment by stephen-carter-at-sf** [comment]
@debprotim Any updates on this? Have you been able to resolve this or do you still need help.

You might want to check to see if you have a .npmrc file that is getting in the way of your machine communicating with the npm registry.

**Comment by stephen-carter-at-sf** [comment]
Closing this issue for now since we haven't received a reply. Feel free to re-open if you still need help.
